### ISSUE TITLE
Playback stopped after 00:00:00 (macOS 10.14.6)

### ISSUE THREAD

**Issue by dsalychev** [MS3FGX/SomaFM#1] opened 2019-10-11 08:36 UTC
I've cloned the repository, installed the both dependencies for python3:
```
$ pip3 show requests
Name: requests
Version: 2.22.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org/
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /usr/local/lib/python3.7/site-packages
Requires: idna, urllib3, chardet, certifi
Required-by: 
```
and
```
$ pip3 show colorama
Name: colorama
Version: 0.4.1
Summary: Cross-platform colored terminal text.
Home-page: https://github.com/tartley/colorama
Author: Jonathan Hartley
Author-email: tartley@tartley.com
License: BSD
Location: /usr/local/lib/python3.7/site-packages
Requires: 
Required-by:
```
There is an mplayer installed via brew also:
```
$ brew info mplayer
mplayer: stable 1.4 (bottled), HEAD
UNIX movie player
https://mplayerhq.hu/
/usr/local/Cellar/mplayer/1.4 (11 files, 29.2MB) *
  Poured from bottle on 2019-10-11 at 10:14:39
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mplayer.rb
==> Dependencies
Build: pkg-config :heavy_check_mark:, yasm ✘
Required: fontconfig :heavy_check_mark:, freetype :heavy_check_mark:, libcaca :heavy_check_mark:
==> Options
--HEAD
    Install HEAD version
==> Analytics
install: 1,381 (30 days), 4,483 (90 days), 26,054 (365 days)
install_on_request: 1,059 (30 days), 3,706 (90 days), 20,953 (365 days)
build_error: 0 (30 days)
```
I was able to obtain a list of the channels via `./somafm.py --list`, but if I start it without arguments or with a specific channels selected I'm getting:
```
Loading stream...OK
-------------------------------
Playback stopped after 00:00:00
```

**Comment by MS3FGX** [comment] 2019-12-05 22:46
Very sorry, for some reason I never got notified when you opened this Issue.

Did you manage to figure anything out with this? Are you able to play the streams with mplayer alone? Something like:

`mplayer -playlist http://somafm.com/defcon256.pls`

It's odd you don't see some kind of error message, if mplayer is crashing or not liking the arguments, those errors should be getting captured and passed on.

**Comment by StoneWaves** [comment] 2020-06-30 11:35
@MS3FGX Just found this and I'm having the same issue with macOS 10.14.6 using mplayer stable 1.4, colorama 0.4.3 and requests 2.24.0.  
I can play fine with the command you listed but trying to run with `somafm` just results in the following.  
```
Loading stream...OK
--------------------------
Playback stopped after 00:00:00
```

Any help would be appreciated.

**Comment by MS3FGX** [comment] 2020-06-30 17:50
Now that there's support for other players, can you try with one of those to see if you get the same result? That might give us an indication if there is some issue with how the script is interacting with MPlayer specifically, or some fundamental flaw in how it's handling the communication with the external player.

Line 84 has the list of supported players in the order they will be tried:

`players = ['mplayer','mpg123','mpv']`

If you remove the mplayer entry, or better yet just make it something like 'xmplayer', it will skip ahead to mpg123 and then mpv.

In the meantime, I'll see if I can add some kind of debugging information and push an update.

**Comment by StoneWaves** [comment] 2020-06-30 19:45
Hmm, appears to be working fine with mpg123 and mpv though the terminal crashes when ctrl+c is pressed.

**Comment by MS3FGX** [comment] 2020-06-30 20:30
Interesting, so it seems like we are looking at an mplayer-specific issue.

I've just pushed an update that will print all the output from the backend media player to the terminal if you run the script with -v or --verbose. Try that with mplayer and maybe we can see some useful information about why it's bailing out.

Also, with mplayer and mpg123 you _should_ be able to just hit Q to stop playback. Ctrl-c should only be necessary for mpv, which itself is a hack because for whatever reason it doesn't want to exit nicely like the other players.

**Comment by StoneWaves** [comment] 2020-07-01 10:14
Running in verbose gives this
```
Loading stream...OK
--------------------------
b'libavformat version 58.27.102 (internal)\n'
b'https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.\n'
b'Failed to open https://api.somafm.com/groovesalad256.pls.\n'
b'Error while opening playlist file https://api.somafm.com/groovesalad256.pls: File exists\n'
b'Error parsing option on the command line: -playlist\n'
b'MPlayer 1.4-4.2.1 (C) 2000-2019 MPlayer Team\n'
Playback stopped after 00:00:00
```
However, I have FFmpeg built with the gnutls option so who knows.
```
  ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

  configuration:
    --prefix=/usr/local/Cellar/ffmpeg/4.3_1
    --enable-shared
    --enable-pthreads
    --enable-version3
    --enable-avresample
    --cc=clang
    --host-cflags=
    --host-ldflags=
    --enable-ffplay
    --enable-gnutls
    --enable-gpl
    --enable-libaom
    --enable-libbluray
    --enable-libdav1d
    --enable-libmp3lame
    --enable-libopus
    --enable-librav1e
    --enable-librubberband
    --enable-libsnappy
    --enable-libsrt
    --enable-libtesseract
    --enable-libtheora
    --enable-libvidstab
    --enable-libvorbis
    --enable-libvpx
    --enable-libwebp
    --enable-libx264
    --enable-libx265
    --enable-libxvid
    --enable-lzma
    --enable-libfontconfig
    --enable-libfreetype
    --enable-frei0r
    --enable-libass
    --enable-libopencore-amrnb
    --enable-libopencore-amrwb
    --enable-libopenjpeg
    --enable-librtmp
    --enable-libspeex
    --enable-libsoxr
    --enable-videotoolbox
    --disable-libjack
    --disable-indev=jack
```

**Comment by MS3FGX** [comment] 2020-07-01 17:25
So I spent a little time looking into this, and apparently mplayer/ffmpeg not supporting HTTPS on Mac OS seems to be a fairly common issue. In fact, it seems this this exact problem has already popped up with another SomaFM player here on GitHub:

https://github.com/uschek/somafm/issues/3

It seems the problem is that brew (presumably that is where you've installed mplayer/ffmpeg from?) no longer includes the --with-openssl option when building ffmpeg:

https://discourse.brew.sh/t/ffmpeg-options-missing/3935

Other posts seem to indicate that resolving the issue could be as simple as running "brew install ffmpeg --with-openssl".

That said, if by default HTTPS links aren't supported when running mplayer on Mac OS, it seems to me that it might make sense for the script to detect the OS and redirect to HTTP if needed. Which is similar what I'm doing with mpg123 already since it doesn't support HTTPS.

I don't think the solution used in the other SomaFM player is actually ideal. He's linking directly to the stream file instead of giving mplayer the playlist, but that means you'll only ever be playing from the one server. Most of the time that would be OK, but if that server goes down you won't get redirected to one of the alternates.

**Comment by MS3FGX** [comment] 2020-07-01 17:56
@StoneWaves I just pushed an update that should detect the mplayer/Mac OS combo, and simply swap out the HTTPS link for HTTP. Let me know if that fixes the issue. 

This seems like the best solution in my mind, and should be fine as long as Soma doesn't decide to drop the older HTTP links in the future. Though we can cross that bridge when we get to it.

**Comment by StoneWaves** [comment] 2020-07-02 10:32
@MS3FGX Thanks for all your help on this issue, I can confirm that the player now works with mplayer using the HTTP link.

**Comment by MS3FGX** [comment] 2020-07-02 18:09
Good to hear. I think we can safely assume that OP was having the same issue so seems we can close this one as fixed.

**Closed by MS3FGX** 2020-07-02 18:09 UTC
